### ISSUE TITLE
GitHub Action that removes "Feature request: " in issue titles and applies the `enhancement` label  (Completed ✅)

### ISSUE THREAD

**Issue by fregante** [sindresorhus/project-ideas#124]
Some users prepend "Feature request", "Bug", "Suggestion", and many other keywords that could be automatically detected and replaced with proper labels.

A workflow example could be:

```yml
on: issue_created

jobs:
  labeler:
    steps:
      - use: you/labeler
        with:
          keywords:
            - feature request
            - suggestion
          labels:
            - enhancement
            - under discussion
      - use: you/labeler
        with:
          keywords:
            - bug
            - bug report
          labels:
            - bug
```
